-- 코드를 입력하세요
SELECT O1.USER_ID, O1.PRODUCT_ID
FROM ONLINE_SALE O1, ONLINE_SALE O2
WHERE O1.ONLINE_SALE_ID != O2.ONLINE_SALE_ID AND O1.USER_ID = O2.USER_ID AND O1.PRODUCT_ID = O2.PRODUCT_ID
GROUP BY USER_ID, PRODUCT_ID
ORDER BY 1, O1.PRODUCT_ID DESC;